# 数据配置
data:
  train_dir: "data/my_dataset/train"
  val_dir: "data/my_dataset/val"
  num_workers: 4
  img_size: 256
  num_classes: 7

# 教师模型配置
teacher:
  checkpoint: "checkpoints/best_teacher.pth"
  feature_dims: [256, 1024]  # 对应resnet50的layer1和layer3输出维度

# 学生模型配置
student:
  arch: "tiny_vit_5m"
  embed_dims: [48, 96, 192, 384]
  depths: [2, 2, 4, 1]
  num_heads: [2, 4, 6, 8]
  window_sizes: [6, 6, 12, 6]
  pretrained: true

# 训练配置
train:
  epochs: 100
  batch_size: 64
  lr: 3e-4
  device: "cuda"
  amp: true  # 启用混合精度

# 蒸馏配置
distill:
  temperature:
    max: 5.0
    min: 1.0
    decay: 0.95
  loss_weights:
    task: 0.5
    kd: 0.3
    feature: 0.2
  early_stop_patience: 5